// Fonte canônica de dados: cidades e bairros da Grande Vitória (SEO local).
// A seção #atendimento no index.html é HTML 100% estático gerado a partir
// deste objeto. Ao editar as listas aqui, regenerar o bloco estático no HTML.
window.BAIRROS_GV = {
    "Vitória": ["Centro", "Jardim da Penha", "Jardim Camburi", "Praia do Canto", "Mata da Praia", "Bento Ferreira", "Enseada do Suá", "Santa Helena", "Santa Lúcia", "Santa Luíza", "Barro Vermelho", "Ilha do Boi", "Ilha do Frade", "Ilha de Santa Maria", "Monte Belo", "Jucutuquara", "Fradinhos", "Horto", "Nazareth", "Parque Moscoso", "Vila Rubim", "Santo Antônio", "Caratoíra", "Bela Vista", "Inhanguetá", "Estrelinha", "Mário Cypreste", "Santa Tereza", "Ariovaldo Favalessa", "Fonte Grande", "Forte São João", "Romão", "Cruzamento", "Ilha das Caieiras", "São Pedro", "Santos Reis", "Redenção", "Nova Palestina", "Resistência", "Conquista", "São José", "Santo André", "Comdusa", "Maria Ortiz", "Solon Borges", "Segurança do Lar", "Antônio Honório", "Boa Vista", "Goiabeiras", "Aeroporto", "Jabour", "Morada de Camburi", "Pontal de Camburi", "República", "Maruípe", "São Cristóvão", "Tabuazeiro", "Bonfim", "Itararé", "Joana D'Arc", "Andorinhas", "Santa Martha", "Santa Cecília", "São Benedito", "Bairro da Penha", "Consolação", "Gurigica", "Praia do Suá", "Santa Clara", "Do Quadro", "Do Cabral", "Universitário", "Piedade", "Do Moscoso"],
    "Vila Velha": ["Centro de Vila Velha", "Praia da Costa", "Itapuã", "Itaparica", "Coqueiral de Itaparica", "Praia de Itaparica", "Glória", "Cristóvão Colombo", "Divino Espírito Santo", "Vila Garrido", "Paul", "Argolas", "São Torquato", "Ataíde", "Cobilândia", "Cobi de Baixo", "Cobi de Cima", "Alvorada", "Jardim Colorado", "Vale Encantado", "Cocal", "Santa Inês", "Ibes", "Araçás", "Jardim Guadalajara", "Jardim Asteca", "Vila Nova", "Novo México", "Soteco", "Guaranhuns", "Jockey de Itaparica", "Pontal das Garças", "Santa Mônica", "Santa Paula", "Nossa Senhora da Penha", "Boa Vista I", "Boa Vista II", "Coqueiral", "Ponta da Fruta", "Barra do Jucu", "Riviera da Barra", "Terra Vermelha", "São Conrado", "Morada da Barra", "Interlagos", "Barramares", "Cidade da Barra", "Jabaeté", "23 de Maio", "Ulisses Guimarães", "João Goulart", "Morada do Sol", "Rio Marinho", "Vale Verde", "Santa Rita", "Aribiri", "Ilha dos Ayres", "Dom João Batista", "Garoto", "Olaria", "Pedra dos Búzios", "Residencial Coqueiral"],
    "Serra": ["Serra Sede", "Laranjeiras", "Parque Residencial Laranjeiras", "Valparaíso", "Colina de Laranjeiras", "Morada de Laranjeiras", "Jardim Limoeiro", "Carapina", "Carapina Grande", "Bairro de Fátima", "Hélio Ferraz", "Manoel Plaza", "Serra Dourada I", "Serra Dourada II", "Serra Dourada III", "Barcelona", "Porto Canoa", "Vista da Serra I", "Vista da Serra II", "Planalto Serrano", "Novo Horizonte", "Feu Rosa", "Vila Nova de Colares", "Jardim Tropical", "Central Carapina", "André Carloni", "Jacaraípe", "Portal de Jacaraípe", "São Francisco", "Castelândia", "Estância Monazítica", "São Patrício", "Costa Dourada", "Bicanga", "Manguinhos", "Nova Almeida", "Praia Grande", "Cidade Continental", "Continental", "Jardim Carapina", "Eurico Salles", "Diamantina", "José de Anchieta", "Parque Res. Mestre Álvaro", "Caçaroca", "Chácara Parreiral", "Taquara I", "Taquara II", "Maringá", "Divinópolis", "Guaraciaba", "Cantinho do Céu", "Balneário de Carapebus", "Bairro das Laranjeiras", "Civit I", "Civit II"],
    "Cariacica": ["Campo Grande", "Itacibá", "Jardim América", "Alto Lage", "São Francisco", "Cruzeiro do Sul", "Vera Cruz", "Porto de Santana", "Flexal I", "Flexal II", "Nova Rosa da Penha", "Nova Canaã", "Castelo Branco", "Vila Capixaba", "Rio Branco", "Santana", "Itaquari", "Jardim Botânico", "Morada de Campo Grande", "Santa Fé", "São Geraldo", "Bela Aurora", "Mucuri", "Itanguá", "Dom Bosco", "Santo André", "São Vicente", "Vasco da Gama", "Padre Mathias", "Tucum", "Sotema", "Nova Valverde", "Valparaíso", "Expedito", "Santa Cecília", "Presidente Médici", "Aparecida", "Bandeirantes", "Oriente", "Maracanã", "Santa Catarina", "Alzira Ramos", "Novo Brasil", "Rosa da Penha", "Piranema"],
    "Viana": ["Viana Sede", "Marcílio de Noronha", "Vila Bethânia", "Nova Bethânia", "Industrial", "Universal", "Arlindo Villaschi", "Areinha", "Primavera", "Canaã", "Vale do Sol", "Soteco de Viana", "Parque Industrial", "Bom Pastor", "Ipanema", "Jucu"],
    "Guarapari": ["Centro de Guarapari", "Muquiçaba", "Praia do Morro", "Meaípe", "Nova Guarapari", "Enseada Azul", "Setiba", "Santa Mônica", "Aeroporto", "Ipiranga", "Jardim Boa Vista", "Kubitschek", "Itapebussu", "Praia dos Padres", "Bela Vista", "São Judas Tadeu", "Village do Sol", "Una", "Perocão", "Santa Margarida"],
    "Fundão": ["Fundão Sede", "Praia Grande de Fundão", "Timbuí", "Encantado", "Piabas", "Praça Oito"]
};
